//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondoSurf_MVC._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Id { get; set; }
        public System.DateTime LogTimeStamp { get; set; }
        public string Url { get; set; }
        public string ErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public string SupplementalInformation { get; set; }
    }
}
