//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondoSurf_MVC._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spot_Forecast
    {
        public int Id { get; set; }
        public int Spot_Id { get; set; }
        public System.DateTimeOffset TimeStampGMT { get; set; }
        public Nullable<double> Size_ft { get; set; }
        public string Shape_Full { get; set; }
        public string Shape_Detail_Swell { get; set; }
        public string Shape_Detail_Tide { get; set; }
        public string Shape_Detail_Wind { get; set; }
        public string Warning { get; set; }
    
        public virtual Spot_Details Spot_Details { get; set; }
    }
}
