//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondoSurf_MVC._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spot_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spot_Details()
        {
            this.Spot_Forecast = new HashSet<Spot_Forecast>();
        }
    
        public int Spot_Id { get; set; }
        public string Spot_Name { get; set; }
        public Nullable<int> County_id { get; set; }
        public string Street_Address { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spot_Forecast> Spot_Forecast { get; set; }
    }
}
